### ISSUE TITLE
configuration-gitops-argocd - add input for sso authentication

### ISSUE THREAD

**Issue by haarchri** [upbound/platform-ref-aws-cnoe#3]
### What happened?
We have to activate Single Sign-On (SSO) authentication with Keycloak in the "configuration-gitops-argocd" settings. To achieve this, we'll add a new input for incorporating the specified details under "server.config.oidc.conf" and "server.url."

```
        config:
          oidc.config: |
            name: Keycloak
            issuer: https://keycloak-<url>/realms/master
            clientID: argocd
            clientSecret: 408fdfcc-dafe-4cca-ac25-124d83076222
            requestedScopes: ['openid', 'profile', 'email', 'groups']
        url: https://keycloak-<url>

```

Epic #
